//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.


export
class EventsAppliedToReadModelEvent
{
	public appliedEventIds: string[];
}
export
class CommandHandlingFeedbackEvent
{
	public commandId: string;
}
export
class AuctionCreatedEvent
{
	public id: string;
	public title: string;
	public description: string;
	public startingPrice: number;
	public minimalPriceForNextBidder: number;
	public createdByUserName: string;
	public endDateTime: string;
}
export
class AuctionFinishedEvent
{
	public auctionId: string;
}
export
class BidMadeEvent
{
	public auctionId: string;
	public bidderUserName: string;
	public bidPrice: number;
	public highestBidderUserName: string;
	public highestBidPrice: number;
	public minimalPriceForNextBidder: number;
}
export
class CommandHandlingSucceededEvent extends CommandHandlingFeedbackEvent
{
	public publishedEventIds: string[];
}
export
class CommandHandlingFailedEvent extends CommandHandlingFeedbackEvent
{
}
