//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.


export
class UserMessageSentEvent
{
	public messageId: string;
	public messageSubject: string;
	public messageBody: string;
	public recipientUserName: string;
	public senderUserName: string;
	public sentDateTime: string;
}
export
class EventsAppliedToReadModelEvent
{
	public appliedEventIds: string[];
}
export
class CommandHandlingFeedbackEvent
{
	public commandId: string;
	public commandSenderUserName: string;
}
export
class AuctionCreatedEvent
{
	public id: string;
	public title: string;
	public description: string;
	public startingPrice: number;
	public minimalPriceForNextBidder: number;
	public createdByUserName: string;
	public endDateTime: string;
	public buyNowPrice: number | null;
	public currentPrice: number;
	public createdDateTime: string;
}
export
class AuctionFinishedEvent
{
	public auctionId: string;
	public finishedDateTime: string;
}
export
class BidMadeEvent
{
	public auctionId: string;
	public bidderUserName: string;
	public bidPrice: number;
	public highestBidderUserName: string;
	public highestBidPrice: number;
	public minimalPriceForNextBidder: number;
	public currentPrice: number;
	public bidDateTime: string;
}
export
class CommandHandlingSucceededEvent extends CommandHandlingFeedbackEvent
{
	public publishedEventIds: string[];
}
export
class CommandHandlingFailedEvent extends CommandHandlingFeedbackEvent
{
}
