//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.


export
class CommandHandlingFeedbackEvent
{
	public commandId: string;
}
export
class AuctionCreatedEvent
{
	public id: string;
	public title: string;
	public description: string;
	public price: number;
}
export
class CommandHandlingSucceededEvent extends CommandHandlingFeedbackEvent
{
	public publishedEventIds: string[];
}
export
class CommandHandlingFailedEvent extends CommandHandlingFeedbackEvent
{
}
