//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.


export
class AuctionListItemReadModel
{
	public id: string;
	public createdByUserName: string;
	public title: string;
	public description: string;
	public endDate: string;
	public buyNowPrice: number;
	public minimalPriceForNextBidder: number;
	public wasFinished: boolean;
	public numberOfBids: number;
}
export
class AuctionsListReadModel
{
	public pageNumber: number;
	public totalPagesCount: number;
	public totalItemsCount: number;
	public pageItems: AuctionListItemReadModel[];
	public pageSize: number;
}
export
class AuctionDetailsReadModel extends AuctionListItemReadModel
{
	public startingPrice: number;
	public highestBidderUserName: string;
}
