//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
"use strict";
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
var AuctionListItemReadModel = (function () {
    function AuctionListItemReadModel() {
    }
    return AuctionListItemReadModel;
}());
exports.AuctionListItemReadModel = AuctionListItemReadModel;
var AuctionListReadModel = (function () {
    function AuctionListReadModel() {
    }
    return AuctionListReadModel;
}());
exports.AuctionListReadModel = AuctionListReadModel;
var AuctionDetailsReadModel = (function (_super) {
    __extends(AuctionDetailsReadModel, _super);
    function AuctionDetailsReadModel() {
        _super.apply(this, arguments);
    }
    return AuctionDetailsReadModel;
}(AuctionListItemReadModel));
exports.AuctionDetailsReadModel = AuctionDetailsReadModel;
//# sourceMappingURL=ReadModel.js.map