//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
var AuctionHouse;
(function (AuctionHouse) {
    var Messages;
    (function (Messages) {
        var Commands;
        (function (Commands) {
            var Auctions;
            (function (Auctions) {
                var CancelAuctionCommand = (function () {
                    function CancelAuctionCommand() {
                    }
                    return CancelAuctionCommand;
                }());
                Auctions.CancelAuctionCommand = CancelAuctionCommand;
                var CreateAuctionCommand = (function () {
                    function CreateAuctionCommand() {
                    }
                    return CreateAuctionCommand;
                }());
                Auctions.CreateAuctionCommand = CreateAuctionCommand;
                var MakeBidCommand = (function () {
                    function MakeBidCommand() {
                    }
                    return MakeBidCommand;
                }());
                Auctions.MakeBidCommand = MakeBidCommand;
            })(Auctions = Commands.Auctions || (Commands.Auctions = {}));
        })(Commands = Messages.Commands || (Messages.Commands = {}));
    })(Messages = AuctionHouse.Messages || (AuctionHouse.Messages = {}));
})(AuctionHouse || (AuctionHouse = {}));
var AuctionHouse;
(function (AuctionHouse) {
    var Messages;
    (function (Messages) {
        var Queries;
        (function (Queries) {
            var Auctions;
            (function (Auctions) {
                var GetAuctionDetailsQuery = (function () {
                    function GetAuctionDetailsQuery() {
                    }
                    return GetAuctionDetailsQuery;
                }());
                Auctions.GetAuctionDetailsQuery = GetAuctionDetailsQuery;
                var GetAuctionListQuery = (function () {
                    function GetAuctionListQuery() {
                    }
                    return GetAuctionListQuery;
                }());
                Auctions.GetAuctionListQuery = GetAuctionListQuery;
            })(Auctions = Queries.Auctions || (Queries.Auctions = {}));
        })(Queries = Messages.Queries || (Messages.Queries = {}));
    })(Messages = AuctionHouse.Messages || (AuctionHouse.Messages = {}));
})(AuctionHouse || (AuctionHouse = {}));
var AuctionHouse;
(function (AuctionHouse) {
    var ReadModel;
    (function (ReadModel) {
        var Auctions;
        (function (Auctions) {
            var List;
            (function (List) {
                var AuctionListItemReadModel = (function () {
                    function AuctionListItemReadModel() {
                    }
                    return AuctionListItemReadModel;
                }());
                List.AuctionListItemReadModel = AuctionListItemReadModel;
                var AuctionListReadModel = (function () {
                    function AuctionListReadModel() {
                    }
                    return AuctionListReadModel;
                }());
                List.AuctionListReadModel = AuctionListReadModel;
            })(List = Auctions.List || (Auctions.List = {}));
        })(Auctions = ReadModel.Auctions || (ReadModel.Auctions = {}));
    })(ReadModel = AuctionHouse.ReadModel || (AuctionHouse.ReadModel = {}));
})(AuctionHouse || (AuctionHouse = {}));
var AuctionHouse;
(function (AuctionHouse) {
    var ReadModel;
    (function (ReadModel) {
        var Auctions;
        (function (Auctions) {
            var Details;
            (function (Details) {
                var AuctionDetailsReadModel = (function (_super) {
                    __extends(AuctionDetailsReadModel, _super);
                    function AuctionDetailsReadModel() {
                        _super.apply(this, arguments);
                    }
                    return AuctionDetailsReadModel;
                }(AuctionHouse.ReadModel.Auctions.List.AuctionListItemReadModel));
                Details.AuctionDetailsReadModel = AuctionDetailsReadModel;
            })(Details = Auctions.Details || (Auctions.Details = {}));
        })(Auctions = ReadModel.Auctions || (ReadModel.Auctions = {}));
    })(ReadModel = AuctionHouse.ReadModel || (AuctionHouse.ReadModel = {}));
})(AuctionHouse || (AuctionHouse = {}));
//# sourceMappingURL=ReinforcedTypingsGeneratedTypes.js.map