//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
"use strict";
var CancelAuctionCommand = (function () {
    function CancelAuctionCommand() {
    }
    return CancelAuctionCommand;
}());
exports.CancelAuctionCommand = CancelAuctionCommand;
var CreateAuctionCommand = (function () {
    function CreateAuctionCommand() {
    }
    return CreateAuctionCommand;
}());
exports.CreateAuctionCommand = CreateAuctionCommand;
var MakeBidCommand = (function () {
    function MakeBidCommand() {
    }
    return MakeBidCommand;
}());
exports.MakeBidCommand = MakeBidCommand;
//# sourceMappingURL=Commands.js.map