//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
"use strict";
/// <reference path="../ReadModel.ts"/>
var GetAuctionDetailsQuery = (function () {
    function GetAuctionDetailsQuery() {
    }
    return GetAuctionDetailsQuery;
}());
exports.GetAuctionDetailsQuery = GetAuctionDetailsQuery;
var GetAuctionListQuery = (function () {
    function GetAuctionListQuery() {
    }
    return GetAuctionListQuery;
}());
exports.GetAuctionListQuery = GetAuctionListQuery;
//# sourceMappingURL=Queries.js.map