//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.


/// <reference path="../ReadModel.ts"/>
export
class GetSentUserMessagesQuery
{
	public pageSize: number;
	public pageNumber: number;
}
export
class GetUserInboxQuery
{
	public pageSize: number;
	public pageNumber: number;
}
export
class GetAuctionDetailsQuery
{
	public id: string;
}
export
class GetAuctionsInvolvingUserQuery
{
	public queryString: string;
	public userInvolvementIntoAuction: any;
	public pageSize: number;
	public pageNumber: number;
}
export
class SearchAuctionsQuery
{
	public queryString: string;
	public pageSize: number;
	public pageNumber: number;
}
